branches:
  only:
  - fuerte
  - groovy
  - hydro
  - master
matrix:
  allow_failures:
  - compiler: clang
notifications:
  email:
  - hpp-source@laas.fr
env:
  global:
    secure: ldI5kV88XCBoLIVeA8sFAeDX+OwAfHpEvfB0cwuSdRKAnhcK4DRsfIYPkQoibZ70AzuWF6OfD84QNcq90hGgDeUFnhnmFy1J5IrPtT3YawYfxvM75jQECgwGPb4v8RSBzzVZEYxGFVJMm8xiBZ7jiN8GjaV2gr22C3dtgOS6HNY=
script: ./.travis/build
before_install: ./.travis/before_install
after_success: ./.travis/after_success
language: cpp
compiler:
- clang
- gcc
